### ISSUE TITLE
Crash when drag and dropping file containing '%' on Log Expert

### ISSUE THREAD

**Issue by petsuter** [zarunbal/LogExpert#15] opened 2017-11-27 13:59 UTC
When a file containing `%` is drag-and-dropped onto Log Expert 1.6.6 it crashes.

**Comment by zarunbal** [comment] 2017-11-28 18:43
Did you start LogExpert like #4 described with Start.cmd? If this problem still apears with the workaround please attach Log (for description see [FAQ](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging)) or EventLogEntries (see [FAQ](https://github.com/zarunbal/LogExpert/wiki/FAQ#event-log)) if the application crashes

**Comment by petsuter** [comment] 2017-11-28 19:12
> Did you start LogExpert like #4 described with Start.cmd?
No.

**Comment by zarunbal** [comment] 2017-11-28 19:24
Please start LogExpert with the Start.cmd and try to reproduce the crash and please give a short feedback if this works for you.

The Drag and Drop Crash is a known bug for which currently a workaround exists.

**Comment by zarunbal** [comment] 2017-12-18 22:41
I asume the drag'n'drop problem is solved with the workaround. 

I'll close this bug because of duplicate to #4

If there are any problems feel free to comment to the appropiate issues or to create a new one.

**Closed by zarunbal** 2017-12-18 22:41 UTC
Labels: duplicate
