### ISSUE TITLE
Cannot close "Could not load file or assembly ChilkatDotNet47, Version=9.5.0.90"

### ISSUE THREAD

**Issue by KoalaBear84** [zarunbal/LogExpert#243] opened 2022-07-20 09:25 UTC
# Bug

Clean install, cannot close LogExpert, and maybe other things not working. See video.

https://user-images.githubusercontent.com/5886900/179947667-b3be30f0-0cb9-4fae-afd8-a34f54dab718.mp4

Could not load file or assembly 'ChilkatDotNet47, Version=9.5.0.90, Culture=neutral, PublicKeyToken=eb5fc1fc52ef09bd' or one of its dependencies. The specified module could not be found.

```
FileNotFoundException
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at LogExpert.Classes.PluginRegistry.LoadPlugins()
   at LogExpert.Classes.PluginRegistry.GetInstance()
   at LogExpert.Classes.LogExpertProxy.WindowClosed(LogTabWindow logWin)
   at LogExpert.Controls.LogTabWindow.LogTabWindow.OnLogTabWindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Hirogen** [comment] 2022-07-20 10:01
Hmm it seems the pluginregistry was not correctly initialized

**Comment by KoalaBear84** [comment] 2022-07-20 10:03
Sorry, didn't see the question as the mail preview only showed the first line.

Is it then also related to #242 ?

**Comment by Hirogen** [comment] 2022-07-20 10:06
I'm currently a little bit buffled, because the PluginRegistry was not initialized, even though as soon as the "LogWindow" is Displayed it will be initilized

**Comment by Hirogen** [comment] 2022-07-20 11:06
> You can easily test it with Windows Sandbox if you have it.

Ah, I never considered that, and yeah, I can reproduce the error with the sandbox version :)

**Comment by Hirogen** [comment] 2022-07-20 11:31
Files: 
- ChilkatDotNet47.dll
- SftpFileSystem.dll
should not be part of the setup, just double checked
#244 
I updated the setup, to remove those 2 dlls, but still need to fix the loading part, so issue will be left open

**Comment by Hirogen** [comment] 2023-03-20 18:08
https://github.com/zarunbal/LogExpert/issues/273
both have the same plugin

**Comment by Hirogen** [comment] 2023-03-23 12:44
fixed with https://github.com/zarunbal/LogExpert/pull/280

**Closed by Hirogen** 2023-03-23 12:44 UTC
Labels: bug
