### ISSUE TITLE
Set columnizer to "Default (single line)" by default?

### ISSUE THREAD

**Issue by scottcopus** [zarunbal/LogExpert#128] opened 2019-08-26 13:58 UTC
How do you set the default columnizer to "Default (single line)" ?

Important questions
- LogExpert Version
1.8.0
- Windows Version
Windows 10 x64 1903
- Lokal file or Network
Network
- Used Columnizer
I'm attempting to set default columnizer to: Default (single line). It opens up some particular log files with Timestamp Columnizer though. Because some of the lines in these particular log files have a space before [DATE TIME], it doesn't columnize those lines correctly.  I'm just trying to default LogExpert to "Default (single line)" for now.
- Is this version specific or a new problem
I assume this is a new issue or maybe by-design behavior.  I have older 1.6.13 on a Win7 computer with what looks like identical settings and it defaults to "Default (single line)".  I'm trying to do the same with latest 1.8.0.

Optional questions(depends on the problem):
- Continous appending log file?
Tailing is fine.
- Size of the file
~100kb
- some specific settings 
Settings | Columnizers is empty, but also tried a file name mask with both blank and * with columnizer set to Default w/o luck.
- Screenshot

# Feature
One "Issue" per feature! If in doubt create a new one.

Please provide a rough use case so its possible to get a deeper understanding how the feature would be used.

# General
Please don't forget, this repository is maintened in free time! The tasks will be tackled as soon as there is time.
No problem! Thanks!
cheers,
Scott

**Comment by Hirogen** [comment] 2019-08-27 09:17
Options => Settings => Columnizers

![image](https://user-images.githubusercontent.com/8225398/63758533-362f7f00-c8bc-11e9-8a89-a82e55e7516a.png)

Do you have anything in there, if yes, delete it, then it should automatically use the "Single Line" Columnizer

**Comment by Groman123** [comment] 2019-08-30 10:40
I have the same problem... 
The suggested solution with having nothing configured in "Options" / "Settings" / "Columnizers" does not work for me.
Also creating a new entry with .* as regex doesn't work for me.

Even restoring the columnizer for a previously opened file doesn't work, but restoring highlight setting works perfect...

**Comment by zarunbal** [comment] 2019-09-19 15:13
It could be for previosly opened files that the previous selected columnizer is used. Just clean the following folder ```<user profile>\Documents\LogExpert\```. Or you can verify for the file which columnizer is saved there, its just a XML file. 

> Even restoring the columnizer for a previously opened file doesn't work, but restoring highlight setting works perfect...

@Groman123 could you please check your [log](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging) file if there are any errors which could indicate a problem?

**Comment by ste22g** [comment] 2019-10-18 13:17
Hi,
with version 1.8.2 the columnizer does not apply the correct formatting to the log file because it does not keep the selection made (in my case CsvColumnizer) if the "automatically save persistence files (.lxp)" option is disabled. In addition it seems that even the file name mask (set in the settings panel) does not work correctly. With version 1.7.17 everything worked correctly.
I attach log file.
ste22g
![lxp](https://user-images.githubusercontent.com/20581673/67097401-509a2080-f1ba-11e9-9c45-2bb6ece8e1bc.jpg)
[logexpert.log](https://github.com/zarunbal/LogExpert/files/3744039/logexpert.log)

**Comment by miltob** [comment] 2019-10-19 12:18
hi @ste22g ,
The issue you mentioned above has been fixed in the PR #135 .
You can try the next release and let me know if you have any question.

**Comment by miltob** [comment] 2019-10-19 12:25
hi @scottcopus ,
The issue you are facing is caused by a feature Auto Columnizer which meant to help user choose a columnizer. When you open a new file, the feature will read the file. In your case, the feature think the file is handled better by Timestamp Columnizer so it was set to it.
At the moment, the feature is always on.
I understand your problem here and planning to create a settings to disable/enable Auto Columnizer.
I'll let you know here once I got any progress.

@zarunbal  Let me know if you have any suggestion.

**Comment by miltob** [comment] 2019-10-19 13:05
@scottcopus  I have created a PR above to support your request.
Add settings to enable/disable auto pick. #137
You can uncheck the new checkbox to keep default columnizer.
![image](https://user-images.githubusercontent.com/42666057/67145427-4c125c80-f2cd-11e9-9871-22844a9260ad.png)

**Comment by zarunbal** [comment] 2020-02-01 00:15
This is fixed in the new release. If you still encounter the problem feel free to reopen the issue

**Closed by zarunbal** 2020-02-01 00:15 UTC
Labels: bug
