### ISSUE TITLE
Highlighting not correctly applied when the line contains a tab \t character

### ISSUE THREAD

**Issue by Otiel** [zarunbal/LogExpert#57] opened 2018-04-18 13:55 UTC
Highlighting is not correctly applied when the line contains a tab `\t` character. It seems that for each `\t` character present on the line, the highlighting is shifted forward by one character.

For instance, with this highlighter:

![image](https://user-images.githubusercontent.com/3851902/38936265-b993a38a-4320-11e8-93e2-ab9687f114f3.png)

I get this result:

![image](https://user-images.githubusercontent.com/3851902/38936154-76e5d044-4320-11e8-8780-302e48656003.png)

Here's the file content:

```
Contains 0 tab - highlight - blabla
\tContains 1 tab - highlight - blabla
\t\tContains 2 tabs - highlight - blabla
\t\t\tContains 3 tabs - highlight - blabla
\t\t\tContains 3 tabs and 1 more here \t- highlight - blabla
         
```

Notes:
- LogExpert Version: current master branch (2018-04-18 15h55)
- Windows Version: Windows 10
- Local file and network file (SFTP plugin)
- Used Columnizer: none

**Comment by zarunbal** [comment] 2018-04-23 19:53
Thanks for your report, this is a interesting Bug. 

I could only imagine that there is something with the replacement of \t with 3 spaces. Maybe this screws the highlighting up.
https://github.com/zarunbal/LogExpert/blob/8bbc7422d95b68dc9b1d633dd3b1b60684765fea/src/ColumnizerLib/Column.cs#L32)

**Comment by zarunbal** [comment] 2018-05-22 21:45
Release 1.6.13 is out there with the fix. I can't reproduce this this mismatch with the highlighting on my machine after the changes. I close this issue. If there is still a problem feel free to reopen this issue.

**Closed by zarunbal** 2018-05-22 21:45 UTC
Labels: bug
