### ISSUE TITLE
Error on startup :Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

### ISSUE THREAD

**Issue by yanivboneh** [zarunbal/LogExpert#127] opened 2019-08-26 07:58 UTC
# Bug

Important questions
- LogExpert Version 1.8
- Windows Version 10
- Ir a new problem

![image](https://user-images.githubusercontent.com/46162157/63674952-63166000-c7f0-11e9-995b-2b665527bfb4.png)

tried uninstalling and reinstalling with  both .exe and building the source

**Comment by Hirogen** [comment] 2019-08-26 13:21
Please copy the complete message from the window and add it as a comment.

**Comment by JatRehm** [comment] 2019-09-02 05:55
The same (or even a similar) issue goes here on two different Windows 10 hosts (1909, x64, German language). There were no such issues with 1.7.1.

The first issue after starting:
![grafik](https://user-images.githubusercontent.com/54790920/64092737-416c2a00-cd56-11e9-944a-899e1a15fb25.png)

After confirmation, the following messagebox appears:
![grafik](https://user-images.githubusercontent.com/54790920/64092838-9445e180-cd56-11e9-8d28-aa7e1a59da8d.png)

**Raw text:**
```
Invoke oder BeginInvoke kann für ein Steuerelement erst aufgerufen werden, wenn das Fensterhandle erstellt wurde.


InvalidOperationException
   bei System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   bei System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   bei LogExpert.LogWindow.SetCurrentHighlightGroup(String groupName)
   bei LogExpert.LogWindow.LoadFile(String fileName, EncodingOptions encodingOptions)
   bei LogExpert.LogWindow.Reload()
   bei LogExpert.LogWindow.SetColumnizerInternal(ILogLineColumnizer columnizer)
   bei LogExpert.LogWindow.SetColumnizer(ILogLineColumnizer columnizer)
   bei LogExpert.LogWindow..ctor(LogTabWindow parent, String fileName, Boolean isTempFile, Boolean forcePersistenceLoading)
   bei LogExpert.LogTabWindow.AddFileTab(String givenFileName, Boolean isTempFile, String title, Boolean forcePersistenceLoading, ILogLineColumnizer preProcessColumnizer, Boolean doNotAddToDockPanel)
   bei LogExpert.LogTabWindow.LogTabWindow_Load(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```


If you need any further info, just let me know.

**Comment by zarunbal** [comment] 2019-10-08 20:07
Can you verify if this error is still there in 1.8.1? 

A short feedback, if the version fixes your problem would be great

**Comment by JatRehm** [comment] 2019-10-09 05:53
I retested the issue in 1.8.1 on several PCs which had the issue with 1.8.0.
Result: The issue is gone; the new version 1.8.1 solved the problem.

Thanks for your good work

**Comment by zarunbal** [comment] 2019-10-09 13:19
Thank you for your feedback. I close this issue

**Closed by zarunbal** 2019-10-09 13:19 UTC
